import {Inter} from "next/font/google";
import "./globals.css";
import {PrimeReactProvider} from 'primereact/api';
import 'primereact/resources/themes/lara-light-indigo/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <PrimeReactProvider>
            {children}
        </PrimeReactProvider>
        </body>
        </html>
    );
}
